"""add agent capabilities

Revision ID: 7aa3a14f62f5
Revises: 11be1feb1e4a
Create Date: 2026-08-12 18:20:30.118580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa3a14f62f5'
down_revision: Union[str, Sequence[str], None] = '11be1feb1e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('capabilities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'capabilities')
    # ### end Alembic commands ###
