"""assign tasks to agents

Revision ID: c07af7416453
Revises: a86a3b225466
Create Date: 2026-08-10 21:41:08.380620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07af7416453'
down_revision: Union[str, Sequence[str], None] = 'a86a3b225466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'agent_id')
    # ### end Alembic commands ###
